version: '3'

services:
  # Setup Client
  web:
    build: ./client
    ports:
      - '3000:3000'
    volumes:
      - ./client/src:/usr/src/app/src:rw
    environment:
      - CHOKIDAR_USEPOLLING=true

  server:
    build: ./server
    ports:
      - '5000:5000'
    volumes:
      - ./server:/usr/src/server:rw
    depends_on:
      - db

  # docker-compose run server rake db:create
  db:
    image: postgres:9.6.2-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db
