version: '3'

services:
  # Setup Client
  web:
    build: ./client
    image: instasham
    ports:
      - '3000:3000'
    volumes:
      - ./client/src:/usr/src/app/src:rw
    environment:
      - CHOKIDAR_USEPOLLING=true

  server:
    build: ./server_rails
    image: rails
    ports:
      - '5000:5000'
    # volumes
  #   depends_on:
  #     - postgres
  #   environment:
  #     DATABASE_URL: postgres://todoapp@postgres/todos
  # postgres:
  #   image: postgres:9.6.2-alpine
  #   environment:
  #     POSTGRES_USER: todoapp
  #     POSTGRES_DB: todos
  # command:
